### ISSUE TITLE
Config deletes skin folder

### ISSUE THREAD

**Issue by Buff555** [Pastisha/EDOPRO-Skinpack#2]
So I tried using the config file in the readme and the skins folder disappeared. Was it supposed to do that?

**Comment by Lahrenheit** [comment]
Yes,  because it will check with git and will be downloaded, check repositories bar in game, let some minutes to finish the downloads

P.s: you cant use or put other skins because they'll overwrite by the config file, if u wont, only download the skin you desire via zip
