### ISSUE TITLE
Error when downloading.

### ISSUE THREAD

**Issue by cooldudemaster** [Pastisha/EDOPRO-Skinpack#4]
Whether I try to download all the skins through git or just let EDOPro download them through the repos, I get errors.
Error I get is, "Error: reference "refs/heads/master" not found."
![imagen](https://github.com/user-attachments/assets/375080c3-4ea8-4dea-b1b3-e7bf2839684b)

For context, I am running Artix Linux. This is not the EDOPro from the AUR, but the "generic" Linux EDOPro downloaded from the original page.

**Comment by Lahrenheit** [comment]
Replied in the other github
